# -*- coding: utf-8 -*-
"""Coba Text Visualization dg Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYpcw18AngLSfqiMrkuMDZzVuOY6wlX7

# Instalasi library yang dibutuhkan
"""

import streamlit as st
from wordcloud import WordCloud
import matplotlib.pyplot as plt

"""# Analisis"""

st.title("Word Cloud Generator")

text = st.text_area("Masukkan teks di sini:")

if st.button("Generate"):
    if text:
        wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
        fig, ax = plt.subplots()
        ax.imshow(wordcloud, interpolation='bilinear')
        ax.axis("off")
        st.pyplot(fig)
    else:
        st.error("Teks tidak boleh kosong!")